### ISSUE TITLE
[app/redpitaya/double_iq_pid_vco] bif file is not generated when make design

### ISSUE THREAD

**Issue by mer0m** [oscimp/app#1]
During disign make:
`bootgen -w -image tmp/double_iq_pid_vco.bif -arch zynq -process_bitstream bin` fails due to bif file not created.

**Comment by trabucayre** [comment]
Hi,
I've just tried to generate this design with a fresh clean repository and I'm unable to reproduce your issue.
Could you provide your vivado version and paste the end of the build?
Thanks

**Comment by mer0m** [comment]
At the end of a `make -j4`:
```
bootgen -w -image tmp/double_iq_pid_vco.bif -arch zynq -process_bitstream bin


****** Xilinx Bootgen v2019.2
  **** Build date : Nov  6 2019-22:01:16
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

[ERROR]  : Can't read file - tmp/double_iq_pid_vco.bif
make: *** [/home/bma/git/github/oscimpDigital/fpga_ip/vivado.mk:39: tmp/double_iq_pid_vco.runs/impl_1/double_iq_pid_vco_wrapper.bit.bin] Error 1
```

But all works after a `make`.
